---
project_name: nats-account-server

release:
  draft: true
  github:
    owner: nats-io
    name: nats-account-server

  name_template: 'Release {{.Tag}}'

builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  env:
  - CGO_ENABLED=0
  ignore:
    - goos: darwin
      goarch: 386

  main: .
  binary: nats-account-server

archives:
  - id: nats-account-server
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
    format: zip
    files:
    - LICENSE
    - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'

dist: dist

github_urls:
  download: https://github.com

