name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [1.21.x]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}

      - name: Install deps
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          go build
          if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then
            echo "gofmt failed; to fix, run: 'go fmt ./...'"
            exit 1
          fi
          go vet ./...
          $HOME/go/bin/staticcheck ./...

      - name: Run tests
        shell: bash --noprofile --norc -x -eo pipefail {0}
        run: |
          # go test -vet=off -v -run=TestNoRace --failfast -p=1 ./...
          # coverage via cov.sh disabled while just testing the waters
          # Also disable race since we are overwhelming the GHA runners.
          go test -vet=off -v -p=1 --failfast ./...
